# Workflow의 이름
name: GitHub Action CI/CD

# 'Event' 기반으로 동작
# develop 브랜치에 push될 경우 아래 Workflow를 실행
on:
  push:
    branches:
      - develop

# 하나의 Workflow는 1개 이상의 Job으로 구성된다.
jobs:
  # 하나의 Job을 식별하기 위한 ID
  My-Job:
    # 사용할 컴퓨터의 OS (latest: 가장 최신 버전)
    runs-on: ubuntu-latest

    # 특정 작업을 수행하는 가장 작은 단위 (작업 세부화)
    steps:
      # name: Step의 이름 (한국어 OK, 영어 OK)
      - name: Hello, World! 작성하기
        # run: 실행하고 싶은 명령어 (OS에 맞는 명령어를 사용해야 함!)
        run: echo "Hello, World!"

      # 여러 줄의 명령어를 입력하고 싶으면 | 기호를 사용하면 된다.
      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Hello"
          echo "World"

      - name: GitHub Secret 사용해보기
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_AGE }}